spring.application.name=learning-support-api
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ho_tro_hoc_tap;encrypt=false

spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuekhanhtin@gmail.com
spring.mail.password=favo gtjj gnaq cebv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jackson.time-zone=Asia/Ho_Chi_Minh

tesseract.datapath=D:/Y4-1/TSR/tessdata
tesseract.language=vie
# Multipart upload config
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.enabled=true

server.port=9090
app.jwt.secret=MY_SUPER_STRONG_SECRET_KEY_2025_ABCXYZ123456!!
app.jwt.expiration-ms=86400000
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
